name: linting, testing, building
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]
jobs:
 pipeline:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node-version: [ 17.x ]

   steps:
     - uses: actions/checkout@v2
     - name: Staring Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node-version }}
     - name: install dependencies
       run: npm ci --force
     - name: linting typescript
       run: npm run lint:ts
       if: always()
     - name: linting styles
       run: npm run lint:style
     - name: unit testing
       if: always()
       run: npm run unit:test
     - name: build storybook
       run: npm run build-storybook
       if: always()
    #  - name: screenshot testing
    #    run: npm run test:ui:ci
    #    if: always()
     - name: build production project
       run: npm run build:prod
       if: always()